server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/se452db
    username: postgres
    password: password

  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

app:
  doc:
    version: 2023-Fall
    title: SE352-452 Concept API3 Production
    description: This is a sample documentation for SE352-452 Concepts a library for OpenAPI 3 with spring boot.
    terms-of-service: http://swagger.io/terms/
    license:  Apache 2.0
    url: http://springdoc.org    
  